#!/usr/bin/env python3
"""Convert a PNG image to LVGL C arrays (RGB565A8 for HW, ARGB8888 for sim)."""
import sys
import os
import struct
from PIL import Image


def clamp(v, lo=0, hi=255):
    return max(lo, min(hi, v))


def rgb565(r, g, b):
    return struct.pack('<H',
        ((clamp(r) >> 3) << 11) |
        ((clamp(g) >> 2) << 5)  |
        (clamp(b) >> 3))


def image_to_lvgl_c(img, var_name):
    """Return (rgb565a8_bytes, width, height) and (argb8888_bytes, width, height)."""
    w, h = img.size
    # Ensure RGBA
    img_rgba = img.convert('RGBA')

    rgb565a8 = bytearray()
    argb8888 = bytearray()

    for y in range(h):
        for x in range(w):
            r, g, b, a = img_rgba.getpixel((x, y))
            # RGB565A8: RGB565 pixels then alpha plane
            rgb565a8.extend(rgb565(r, g, b))
            rgb565a8.append(clamp(a))
            # ARGB8888: A R G B (native byte order)
            argb8888.extend(struct.pack('BBBB', clamp(a), clamp(r), clamp(g), clamp(b)))

    return (bytes(rgb565a8), w, h), (bytes(argb8888), w, h)


def generate_c_source(rgb565a8_data, argb8888_data, w, h, var_name):
    lines = []
    lines.append(f'/* Auto-generated by convert_logo.py — DO NOT EDIT */')
    lines.append(f'/* Image: {w}×{h} */')
    lines.append(f'#include "lvgl.h"')
    lines.append('')

    # RGB565A8 array (for hardware, LV_COLOR_DEPTH=16)
    lines.append(f'#if LV_COLOR_DEPTH == 16')
    lines.append(f'static const uint8_t {var_name}_rgb565a8_data[] = {{')
    for i in range(0, len(rgb565a8_data), 16):
        chunk = rgb565a8_data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'  {hex_vals},')
    lines.append(f'}};')
    lines.append('')
    lines.append(f'const lv_img_dsc_t {var_name} = {{')
    lines.append(f'  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,')
    lines.append(f'  .header.always_zero = 0,')
    lines.append(f'  .header.reserved = 0,')
    lines.append(f'  .header.w = {w},')
    lines.append(f'  .header.h = {h},')
    lines.append(f'  .data_size = {len(rgb565a8_data)},')
    lines.append(f'  .data = {var_name}_rgb565a8_data,')
    lines.append(f'}};')
    lines.append(f'#endif')
    lines.append('')

    # ARGB8888 array (for simulator, LV_COLOR_DEPTH=32)
    lines.append(f'#if LV_COLOR_DEPTH == 32')
    lines.append(f'static const uint8_t {var_name}_argb8888_data[] = {{')
    for i in range(0, len(argb8888_data), 16):
        chunk = argb8888_data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'  {hex_vals},')
    lines.append(f'}};')
    lines.append('')
    lines.append(f'const lv_img_dsc_t {var_name} = {{')
    lines.append(f'  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,')
    lines.append(f'  .header.always_zero = 0,')
    lines.append(f'  .header.reserved = 0,')
    lines.append(f'  .header.w = {w},')
    lines.append(f'  .header.h = {h},')
    lines.append(f'  .data_size = {len(argb8888_data)},')
    lines.append(f'  .data = {var_name}_argb8888_data,')
    lines.append(f'}};')
    lines.append(f'#endif')
    lines.append('')

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <input.png> <max_width> <max_height> <var_name> [output_dir]")
        sys.exit(1)

    in_path = sys.argv[1]
    w = int(sys.argv[2])
    h = int(sys.argv[3])
    var_name = sys.argv[4]
    out_dir = sys.argv[5] if len(sys.argv) > 5 else os.path.dirname(in_path)

    img = Image.open(in_path).convert('RGBA')
    bbox = img.getbbox()
    if bbox:
        img = img.crop(bbox)

    cw, ch = img.size
    scale = min(w / cw, h / ch)
    w, h = max(1, round(cw * scale)), max(1, round(ch * scale))
    img = img.resize((w, h), Image.LANCZOS)

    (rgb565a8, _, _), (argb8888, _, _) = image_to_lvgl_c(img, var_name)
    c_src = generate_c_source(rgb565a8, argb8888, w, h, var_name)

    base = os.path.splitext(os.path.basename(in_path))[0]
    out_path = os.path.join(out_dir, f'{var_name}.c')
    with open(out_path, 'w') as f:
        f.write(c_src)
    print(f'Generated {out_path} ({w}×{h}, RGB565A8={len(rgb565a8)}B, ARGB8888={len(argb8888)}B)')


if __name__ == '__main__':
    main()
